yarn add gatsby-plugin-sharp
Netlify build is failing with following errors:

error Plugin gatsby-transformer-remark returned an error

  Error: Cannot find module 'gatsby-plugin-sharp'

  - v8-compile-cache.js:159 require
    [repo]/[v8-compile-cache]/v8-compile-cache.js:159:20

failed during stage 'building site': Build script returned non-zero exit code: 1
  - index.js:26 Object.<anonymous>
Shutting down logging, 50 messages pending